Modules/Amirhossein/Http/routes.php
<?php

use Modules\Amirhossein\Providers\RouteServiceProvider;

/*
|--------------------------------------------------------------------------
| Manage
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware' => 'web'], function () {

    Route::group(
        [
            'middleware' => ['auth', 'is:admin'],
            'prefix'     => 'manage/amirhossein',
            'namespace'  => 'Modules\Amirhossein\Http\Controllers\Manage',
        ],
        function () {
            /*
            |--------------------------------------------------------------------------
            | Drawing
            |--------------------------------------------------------------------------
            |
            */
            Route::group(['prefix' => 'draw'], function () {
                Route::get('{hashid}', 'DrawingController@draw')
                    ->name('amirhossein.draw');
                Route::get('{hashid}/winners', 'DrawingController@winners')
                    ->name('amirhossein.draw.winners');
                Route::post('prepare', 'DrawingController@prepareForDraw')
                    ->name('amirhossein.draw.prepare');
                Route::post('select', 'DrawingController@select')
                    ->name('amirhossein.draw.select');
                Route::get('act/{hashid}/{viewFile}', 'DrawingController@singleAction')
                    ->name('amirhossein.draw.act');
                Route::get('delete/{key}', 'DrawingController@delete')
                    ->name('amirhossein.draw.delete');
            });
        }
    );


    Route::group([
        'namespace' => 'Modules\Amirhossein\Http\Controllers\Auth',
    ],
        function () {
            Route::get('login', 'LoginController@showLoginForm')->name('login');
            Route::get('home', 'LoginController@home')->name('home');

            Route::get('register', 'RegisterController@showRegistrationForm')->name('register');

            Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        }
    );

    Route::get('pay/{cart}', 'Modules\Amirhossein\Http\Controllers\PurchaseController@paymentShortLink');

    Route::group(
        ['middleware' => ['locale'], 'namespace' => 'Modules\Amirhossein\Http\Controllers'],
        function () {
            Route::get('/', 'FrontController@index')->name('amirhossein.front');
            Route::group(
                [
                    'prefix' => '{lang}',
                    'where'  => ['lang' => '[^\/_][^\/]*+'],
                ], function ($router) {
                    Route::group([
                    'namespace' => 'Auth',
                ],
                    function () {
                        Route::get('login', 'LoginController@showLoginForm');
                        Route::post('login', 'LoginController@login');

                        Route::get('register', 'RegisterController@showRegistrationForm');
                        Route::post('register', 'RegisterController@register');

                        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm');
                        Route::post('password/reset', 'ResetPasswordController@reset');
                        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
                        //Route::post('password/email', 'ForgotPasswordController@showLinkRequestForm')->name('password.email');

                        Route::get('password/token/{haveCode?}', 'ResetPasswordController@getToken');
                        Route::post('password/token', 'ResetPasswordController@checkToken');
                        Route::get('password/new', 'ResetPasswordController@newPassword');
                        Route::post('password/new', 'ResetPasswordController@changePassword');
                    }
                );

                    Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
                        Route::get('dashboard', 'UserController@index')->name('amirhossein.user.dashboard');

                        Route::get('orders', 'UserController@orders')->name('amirhossein.user.orders');
                        Route::get('orders/{order}/info', 'UserController@orderInfo')->name('amirhossein.user.order.info');

                        Route::get('profile', 'UserController@profile')->name('amirhossein.user.profile');
                        Route::post('profile', 'UserController@update')->name('amirhossein.user.profile.update');

                        Route::get('drawing', 'UserController@drawing')->name('amirhossein.user.drawing');

                        Route::get('events', 'UserController@events')->name('amirhossein.user.events');

                        Route::get('addresses', 'UserController@addresses')->name('amirhossein.user.addresses');
                        Route::get('addresses/{hashid}', 'UserController@addressesRow')
                        ->name('amirhossein.user.addresses.row');
                        //            Route::get('/dashboard/previous_comments/{post_id}', 'UserController@previousComments');
                    });

                    Route::group(['prefix' => 'address', 'middleware' => 'auth'], function () {
                        Route::post('save', 'AddressController@save')->name('amirhossein.address.save');
                    });

                    Route::group(['prefix' => 'cart'], function () {
                        Route::get('/', 'CartController@index')->name('amirhossein.cart');
                        Route::get('flush', 'CartController@flush')->name('amirhossein.cart.flush');
                        Route::post('modify', 'CartController@modifyCart')->name('amirhossein.cart.modify');

                        Route::group(['prefix' => 'item'], function () {
                            Route::post('add', 'CartController@addItem')->name('amirhossein.cart.item.add');
                            Route::post('remove', 'CartController@removeItem')->name('amirhossein.cart.item.remove');
                            Route::post('{hashid}', 'CartController@modifyItem')->name('amirhossein.cart.item.modify');
                        });

                        Route::group(['prefix' => 'view'], function () {
                            Route::get('reload', 'CartController@reloadView')->name('amirhossein.cart.view.reload');
                        });
                    });

                    Route::group(['prefix' => 'purchase'], function () {
                        Route::get('user', 'PurchaseController@step1')->name('amirhossein.purchase.step1');

                        Route::group(['middleware' => 'auth'], function () {
                            Route::get('shipping', 'PurchaseController@step2')->name('amirhossein.purchase.step2');
                            Route::get('shipping/content', 'PurchaseController@reloadStep2')
                            ->name('amirhossein.purchase.step2.content');
                            Route::get('shipping/verify', 'PurchaseController@verifyStep2')
                            ->name('amirhossein.purchase.step2.verify');

                            Route::get('review', 'PurchaseController@step3')->name('amirhossein.purchase.step3');
                            Route::get('review/verify', 'PurchaseController@verifyStep3')
                            ->name('amirhossein.purchase.step3.verify');

                            Route::get('pay', 'PurchaseController@step4')->name('amirhossein.purchase.step4');

                            Route::post('final', 'PurchaseController@final')->name('amirhossein.purchase.final');

                            Route::get('payment/result/{cart}', 'PurchaseController@paymentCallback')
                                ->middleware('ownCart')
                                ->name('amirhossein.purchase.paymentResult');
                        });
                    });

                    Route::group(['prefix' => 'payment'], function () {
                        Route::post('repurchase/{transaction}', 'PaymentController@repurchase')
                        ->name('amirhossein.payment.repurchase');
                        Route::get('fire/{transaction}', 'PaymentController@fire')
                        ->name('amirhossein.payment.fire');
                        Route::post('declare/{transaction}', 'PaymentController@declare')
                        ->name('amirhossein.payment.declare');
                    });

                    Route::group(['prefix' => 'purchase'], function () {
                        Route::get('reload', 'CartController@reloadView')->name('amirhossein.cart.view.reload');
                    });


                    Route::group(['prefix' => 'province'], function () {
                        Route::get('cities/{province}/select', 'ProvinceController@getProvinceCitiesSelect')
                        ->name('amirhossein.province.cities.select');
                    });

                    Route::get('events/{type}', 'PostController@eventsAjax')
                    ->name('amirhossein.eventsAjax')
                    ->where('type', '^(waiting|expired){1,1}$');

                    Route::group(['prefix' => 'drawing-code'], function () {
                        Route::post('submit', 'DrawingController@submitCode')->name('amirhossein.drawing-code.submit');
                    });

                    Route::get('contact', 'FrontController@contact')->name('amirhossein.contact');

                    Route::get('products/search', 'PosttypeController@productsSearch')
                    ->name('amirhossein.products.list');

                    Route::group(['prefix' => 'archive'], function () {
                        Route::get('{posttype}/categories', 'PosttypeController@showCategories')
                        ->name('amirhossein.posttype.showCategories');

Modules/Amirhossein/Entities/Drawing.php
<?php

namespace Modules\Amirhossein\Entities;

use Modules\Yasna\Services\YasnaModel;

class Drawing extends YasnaModel
{
    protected $guarded = ['id'];
    public $timestamps = false;

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public static function prepareDatabase($post)
    {
        self::truncate();
        Receipt::withTrashed()->update([
            'operation_integer' => 0,
        ]);
        $post->receipts()->groupBy('user_id')->update([
            'operation_integer' => 1,
        ]);

        session()->put('line_number', '0');
        session()->put('drawing_post', $post->id);
    }

    public static function pull($number)
    {
        return self::where('lower_line', '<=', $number)->where('upper_line', '>=', $number)->first();
    }

    public static function isReady($post_id)
    {
        return boolval(session()->get('drawing_post') == $post_id and session()->get('line_number') > 0);
    }
}

Modules/Amirhossein/Entities/Receipt.php
<?php

namespace Modules\Amirhossein\Entities;

use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Yasna\Services\YasnaModel;

class Receipt extends YasnaModel
{
    use SoftDeletes;

    protected $fillable = [];
    protected $guarded = ['id'];

    /*
    |--------------------------------------------------------------------------
    | Accessors and Mutators
    |-------------------------------------------------------------------------
    |
    */

    public function getDashedCodeAttribute()
    {
        // separator
        $dashed_code = '';
        $uniq_code   = str_split($this->code);
        for ($i = 0; $i <= 19; $i++) {
            if ($i == 4 or $i == 9 or $i == 14) {
                $seperator = '-';
            } else {
                $seperator = '';
            }
            $dashed_code .= $uniq_code[ $i ] . $seperator;
        }

        return $dashed_code;
    }

    public function getAmountFormatAttribute()
    {
        if ($this->purchased_amount > 0) {
            return number_format($this->purchased_amount);
        } else {
            return 0;
        }
    }
}

Modules/Amirhossein/Http/Controllers/DrawingController.php
<?php

namespace Modules\Amirhossein\Http\Controllers;

use App\Models\Receipt;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Amirhossein\Http\Requests\DrawingCodeSubmitRequest;
use Modules\Amirhossein\Providers\DrawingCodeServiceProvider;
use Modules\Amirhossein\Services\Module\CurrentModuleHelper;

class DrawingController extends Controller
{
    protected static $tryingLimit = 100;

    public function submitCode(DrawingCodeSubmitRequest $request)
    {
        $code = $request->code;
        $response = [];
        $continue = true;
        $count = 1;

        if ($request->session()->get('drawing_try')) {
            $try = $request->session()->get('drawing_try');
            $count = $try['count'];

            if ($count > self::$tryingLimit) {
                $continue = false;
            }

            $response['status'] = 'fail';
            $response['msg'] = CurrentModuleHelper::trans('general.drawing.message.invalid-code');
            $response['abc'] = 1;
        } else {
            $request->session()->put(
                'drawing_try',
                [
                    'count' => $count,
                    'last' => Carbon::now()->toDateTimeString(),
                ]);
        }

        if (DrawingCodeServiceProvider::checkCode($code) && $continue) {
            $foundReceipt = Receipt::where('code', $code)->get();
            if ($foundReceipt and $foundReceipt->count()) {
                $response['status'] = 'fail';
                $response['msg'] = CurrentModuleHelper::trans('general.drawing.message.invalid-code');
                $response['abc'] = 2;

                $try = $request->session()->get('drawing_try');
                $try['count'] = $try['count'] + 1;
                $request->session()->put('drawing_try', $try);
            } else {
                $request->session()->put('drawingCode', encrypt($code));
                $response['status'] = 'success';
                $response['msg'] = CurrentModuleHelper::trans('general.drawing.message.register-code-success-please-wait');
                $response['login'] = user()->exists;
            }
        } else {
            $try = $request->session()->get('drawing_try');
            $try['count'] = $try['count'] + 1;
            $request->session()->put('drawing_try', $try);

            $response['status'] = 'fail';
            $response['msg'] = CurrentModuleHelper::trans('general.drawing.message.invalid-code');
            $response['abc'] = 3;
        }

        return \response()->json($response);
    }
}

Modules/Amirhossein/Resources/views/user/drawing/form.blade.php
<!-- Add code modal -->
<div class="modal-wrapper">
    <section class="panel modal sm add-code" id="add-code-modal">
        <article>
            <h2> {{ CurrentModule::trans('general.drawing.code.register') }} </h2>
            <form class="form-horizontal" id="drawing-form">
                {{ csrf_field() }}
                <div class="gift-inputs">
                    <input type="text" class="gift-input" maxlength="26" id="gift-input" placeholder="-----  -----  -----  -----"
                           style="width: 100%;direction: ltr">
                </div>
                <div class="action">
                    <button class="block green" type="button" onclick="drawingCode();">
                        {{ CurrentModule::trans('general.drawing.code.check') }}
                    </button>
                </div>
                <div class="result">
                    <div class="result-item" style="display: none;"></div>
                </div>
            </form>
        </article>
    </section>
</div>

Modules/Amirhossein/Resources/views/user/drawing/main.blade.php
@extends(CurrentModule::bladePath('user.frame.main'))

@php
    $activeTab = 'drawings';
    Template::appendToPageTitle(CurrentModule::trans('general.drawing.code.registered-plural'));
    Template::appendToNavBar([
        CurrentModule::trans('general.drawing.code.registered-plural'), CurrentModule::actionLocale('UserController@drawing')
    ]);
@endphp

@section('dashboard-body')
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-center">
                <section class="panel">
                    <header>
                        <div class="title">
                            <span class="icon-tag"></span>
                            {{ CurrentModule::trans('general.drawing.code.registered-plural') }}
                        </div>
                        <div class="functions">
                            <button class="blue" data-modal="add-code-modal">
                                {{ CurrentModule::trans('general.drawing.code.add') }}
                            </button>
                        </div>
                    </header>
                    <article>
                        @if(!array_default(\App\Models\User::getRequiredFields(), user()->toArray()))
                            <div class="alert alert-danger text-right">
                                {{ CurrentModule::trans('user.message.complete-to-join-drawing') }}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{{ CurrentModule::actionLocale('UserController@profile') }}">
                                    {{ CurrentModule::trans('user.edit-profile') }}
                                </a>
                            </div>
                        @endif

                        @if($receipts->count())
                            <table class="table">
                                <thead>
                                <tr>
                                    <th> {{ CurrentModule::trans('general.drawing.code.singular') }} </th>
                                    <th> {{ CurrentModule::trans('form.created-at') }} </th>
                                    <th> {{ CurrentModule::trans('form.purchased-at') }} </th>
                                    <th>
                                        {{ CurrentModule::trans('form.amount') }}
                                        ({{ CurrentModule::trans('general.unit.currency.IRR') }})
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($receipts as $receipt)
                                    <tr>
                                        <td class="fw-b color-green">{{ ad($receipt->dashed_code) }}</td>
                                        <td> {{ ad(echoDate($receipt->created_at, 'j F Y')) }} </td>
                                        <td> {{ ad(echoDate($receipt->purchased_at, 'j F Y')) }} </td>
                                        <td> {{ ad($receipt->amount_format) }} </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper mt20">
                                {!! $receipts->render() !!}
                            </div>
                        @else
                            <div class="alert red">
                                {{ CurrentModule::trans('user.message.drawing-code-not-found') }}
                            </div>
                        @endif
                    </article>
                </section>
                @include(CurrentModule::bladePath('user.drawing.form'))
            </div>
        </div>
    </div>
    @include(CurrentModule::bladePath('user.drawing.scripts'))
@append

Modules/Amirhossein/Resources/views/user/drawing/scripts.blade.php
@section('html-footer')
    @include(CurrentModule::bladePath('layouts.widgets.form.scripts'))
    <script>
        let drawingVars = {
            routes: {
                submit: "{{ CurrentModule::actionLocale('DrawingController@submitCode') }}",
                userDrawings: "{{ CurrentModule::actionLocale('UserController@drawing') }}",
                register: "{{ route('register') }}",
            },
            messages: {
                invalidCode: "{{ CurrentModule::trans('general.drawing.message.invalid-code') }}"
            }
        };
    </script>
    {!! Html::script(CurrentModule::asset('js/drawing.min.js')) !!}
@append